# ==========================================
# AUTO-GENERATED BY VN HELPER RPA ENCRYPTOR
# ==========================================
init python:
    # --- DEKLARASI ARSIP ---
    build.archive('archive', 'all')
    build.archive('audio', 'all')
    build.archive('gui', 'all')
    build.archive('images', 'all')
    build.archive('libs', 'all')

    # --- ANTI-LEAK EXCLUSIONS ---
    build.classify('**~', None)
    build.classify('**.bak', None)
    build.classify('**.psd', None)
    build.classify('**.kra', None)
    build.classify('**.docx', None)

    # --- MOD-FRIENDLY ZONE ---
    build.classify('game/mods/**', 'all')

    # --- PEMETAAN FOLDER KE ARCHIVE ---
    build.classify('game/audio/**.png', 'audio')
    build.classify('game/audio/**.ogg', 'audio')
    build.classify('game/gui/**.png', 'gui')
    build.classify('game/gui/**.ogg', 'gui')
    build.classify('game/images/**.png', 'images')
    build.classify('game/images/**.ogg', 'images')
    build.classify('game/libs/**.png', 'libs')
    build.classify('game/libs/**.ogg', 'libs')